CREATE DATABASE IF NOT EXISTS LSG_Bars DEFAULT CHARACTER SET 'utf8mb4' DEFAULT COLLATE 'utf8mb4_general_ci';

USE LSG_Bars;

CREATE TABLE IF NOT EXISTS PERSONA(
    DNI VARCHAR (9),
    Nom VARCHAR (30),
    Cognom1 VARCHAR (30),
    Cognom2 VARCHAR (30),
    Email VARCHAR (30),
    PRIMARY KEY (DNI),
    UNIQUE (Email)
);

CREATE TABLE IF NOT EXISTS CARREC_EMPLEAT(
   Nom_carrec VARCHAR (30),
   Descripcio VARCHAR (30),
   Hores_contracte INT,
   Sou_base DECIMAL(2),
   PRIMARY KEY (Nom_carrec)
);

CREATE TABLE IF NOT EXISTS LOCALITAT(
    Id_lloc INT UNSIGNED AUTO_INCREMENT,
    Nom_localitat INT,
    Provincia VARCHAR (30),
    Comunitat_autonoma VARCHAR (30),
    Pais VARCHAR (30),
    Continent VARCHAR (30),
    PRIMARY KEY (Id_lloc)
);

CREATE TABLE IF NOT EXISTS EMPLEAT(
    DNI_Empleat VARCHAR (9),
    Num_SS VARCHAR (12),
    Num_CC VARCHAR (24),
    Quantitat_sou_extra INT,
    Nom_carrec VARCHAR (30),
    DNI_cap VARCHAR (9),
    Lloc_naixement INT UNSIGNED,
    PRIMARY KEY(DNI_Empleat),
    FOREIGN KEY (DNI_Empleat) REFERENCES PERSONA(DNI) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CLIENT(
    DNI_Client VARCHAR(9),
    Es_Major BOOLEAN,
    PRIMARY KEY (DNI_Client),
    FOREIGN KEY (DNI_Client) REFERENCES CLIENT(DNI_Client) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (DNI_Client) REFERENCES PERSONA(DNI) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS BAR(
    Id_bar INT UNSIGNED AUTO_INCREMENT,
    Nom VARCHAR(30),
    Aforament_maxim INT,
    Te_exterior BOOLEAN,
    Ubicacio INT,
    PRIMARY KEY (Id_bar)
);

CREATE TABLE IF NOT EXISTS TAULA(
    Numero_Taula INT UNSIGNED,
    Id_Bar INT UNSIGNED,
    Es_exterior BOOLEAN,
    Es_fumadors BOOLEAN DEFAULT false,
    Num_cadires INT,
    PRIMARY KEY (Numero_Taula),
    FOREIGN KEY (Id_Bar) REFERENCES BAR(Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CLIENT_TAULA(
    Id_client_taula INT UNSIGNED AUTO_INCREMENT,
    DNI_Client VARCHAR(9),
    Numero_Taula INT UNSIGNED,
    Id_Bar INT UNSIGNED,
    Es_fumador BOOLEAN DEFAULT 0,
    Data_hora_arribada DATETIME,
    Data_hora_sortida DATETIME,
    Ha_pagat BOOLEAN,
    PRIMARY KEY (Id_client_taula),
    FOREIGN KEY (Numero_Taula, Id_Bar) REFERENCES TAULA(Numero_Taula, Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DISTRIBUIDOR(
    Id_Distribuidor INT UNSIGNED AUTO_INCREMENT,
    Nom_empresa VARCHAR(30),
    Contacte_principal VARCHAR(30),
    Telefon INT,
    Email VARCHAR(30),
    Web VARCHAR(30),
    PRIMARY KEY (Id_Distribuidor)
);

CREATE TABLE IF NOT EXISTS TAPA(
    Id_Tapa INT UNSIGNED AUTO_INCREMENT,
    Nom VARCHAR(30),
    Descripcio_carta VARCHAR (30),
    Temps_preparacio DATETIME,
    Es_Calent BOOLEAN,
    Es_Vegeta BOOLEAN,
    Es_Individual BOOLEAN,
    PRIMARY KEY (Id_Tapa)
);

CREATE TABLE IF NOT EXISTS BEGUDA(
    Id_Beguda INT UNSIGNED AUTO_INCREMENT,
    Nom VARCHAR(30),
    Descripcio VARCHAR(30),
    Es_Calent BOOLEAN,
    Te_alchol BOOLEAN,
    Quantitat_CL INT,
    PRIMARY KEY (Id_Beguda)
);

CREATE TABLE IF NOT EXISTS DISTO_BEGUDA( 
    Id_Distribuidor INT UNSIGNED,
    Id_Beguda INT UNSIGNED,
    Cost_venda FLOAT(2),
    PRIMARY KEY (Id_Distribuidor, Id_Beguda),
    FOREIGN KEY (Id_Distribuidor) REFERENCES DISTRIBUIDOR(Id_Distribuidor) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Id_Beguda) REFERENCES BEGUDA(Id_Beguda) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS INGREDIENT(
    Id_Ingredient INT UNSIGNED AUTO_INCREMENT,
    Nom VARCHAR(30),
    Descripcio VARCHAR(30),
    Es_Picant BOOLEAN,
    Es_importacio BOOLEAN,
    Cost_gram FLOAT(2),
    Id_Distribuidor INT UNSIGNED,
    PRIMARY KEY (Id_Ingredient),
    FOREIGN KEY (Id_Distribuidor) REFERENCES DISTRIBUIDOR(Id_Distribuidor) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS INGRADIENT_TAPA(
    Id_Ingredient INT UNSIGNED,
    Id_Tapa INT UNSIGNED,
    Quantitat INT,
    PRIMARY KEY (Id_Ingredient, Id_Tapa),
    FOREIGN KEY (Id_Tapa) REFERENCES TAPA(Id_Tapa) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Id_Ingredient) REFERENCES INGREDIENT(Id_Ingredient) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CARTA_TAPES(
    Id_Tapa INT UNSIGNED,
    Id_Bar INT UNSIGNED,
    Cost DECIMAL(2),
    PVP DECIMAL(2),
    PRIMARY KEY (Id_Tapa, Id_Bar),
    FOREIGN KEY (Id_Tapa) REFERENCES TAPA(Id_Tapa) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (Id_Bar) REFERENCES BAR(Id_BAR) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS CARTA_BEGUDES(
    Id_Beguda INT UNSIGNED,
    Id_Bar INT UNSIGNED,
    Cost DECIMAL(2),
    PVP DECIMAL(2),
    PRIMARY KEY (Id_Beguda, Id_Bar),
    FOREIGN KEY (Id_Beguda) REFERENCES BEGUDA(Id_Beguda) ON UPDATE RESTRICT ON DELETE RESTRICT,
    FOREIGN KEY (Id_Bar) REFERENCES BAR(Id_Bar) ON UPDATE RESTRICT ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS COMANDA_TAPES(
    Id_Tapa INT UNSIGNED,
    Id_Bar INT UNSIGNED,
    Id_client_taula INT UNSIGNED,
    Data_hora_comanda DATETIME,
    Quantitat INT,
    PRIMARY KEY (Id_Tapa, Id_Bar),
    FOREIGN KEY (Id_Tapa, Id_Bar) REFERENCES CARTA_TAPES(Id_Tapa, Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Id_client_taula) REFERENCES CLIENT_TAULA(Id_client_taula) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS COMANDA_BEGUDES(
    Id_Beguda INT UNSIGNED,
    Id_Bar INT UNSIGNED,
    Id_client_taula INT UNSIGNED,
    Data_hora_comanda DATETIME,
    Quantitat INT,
    PRIMARY KEY (Id_Beguda, Id_Bar),
    FOREIGN KEY (Id_Beguda, Id_Bar) REFERENCES CARTA_BEGUDES(Id_Beguda,Id_Bar) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Id_client_taula) REFERENCES CLIENT_TAULA(Id_client_taula) ON UPDATE CASCADE ON DELETE CASCADE
);